### ISSUE TITLE
[Docs]Version/Tag consistency with npm registry

### ISSUE THREAD

**Issue by JasonBoy** [lemonce/svg-captcha#10]
Looks like the tags here are not synced with the versions you published on npm registry, it could be better to sync with all the version there, and maybe some changelog for every version?

**Comment by steambap** [comment]
Yes, I'm pretty sloppy with the tag here on github.
When I work on a node project, I usually npm install or yarn add and done. There's why I do not care much about the tag on github.
As for the changelog, it's all in the commit message. However, I have to admit that it will be helpful for developers to see the changelog in a more convenient way

**Comment by steambap** [comment]
PRs for docs are welcomed.
