### ISSUE TITLE
The text places not in center of image

### ISSUE THREAD

**Issue by toltek7** [lemonce/svg-captcha#12]
**Which version of svg-captcha are you using?**
1.3.8
**Do you want to request a *feature* or report a *bug*?**
bug
**If this is a feature request, what is motivation for changing the behavior?**

**If it is a bug, which version of svg-captcha are you using?**
1.3.8
**What is the current behavior?**
text places above the image (my text with custom fonts not centered, but placed at the top of image, sometimes cutoff) - https://www.screencast.com/t/HKAKKL4bc
**What is the expected behavior?**
text should be centered - https://www.screencast.com/t/QFXswdxZ
**Step to reproduce the bug or other relevant information**
please see line 37 in index.js (	const y = height / 2;) more properly value (	(height + options.fontSize) / 2;) https://www.screencast.com/t/maTW9HrzjS

**Comment by steambap** [comment]
What is the name of the font you are using? Can I download it somewhere?

**Comment by toltek7** [comment]
Yes, you can get it by this link - https://www.dropbox.com/s/bybh74j4sj5752v/test-font%2B.ttf?dl=0
But you know that, i tried to use another font - https://www.dropbox.com/s/bnzepmtq4vj45do/test-font.ttf?dl=0 (similar to the first one) and i do not see an issue with it.

So, may be the problem in font itself (in chars line-height or else, i'm not a specialist in fonts). If you have an idea why does this happen, please let me know. If the problem really in font let's close this issue (i will create workaround locally with only the font i need)

**Comment by steambap** [comment]
I got 403 forbidden when visiting your link.

Can you try version 1.3.9 to see if it is fixed?

**Comment by toltek7** [comment]
In 1.3.9 the same problem, send you two fonts on email 93458**@qq.com. Please let me know if need to send on another email.

**Comment by steambap** [comment]
I saw your email.

**Comment by toltek7** [comment]
After reinstalling node packages img looks better in version 1.3.9. But still not centered. Based on our conversation with steambap it cannot be fixed rather than adding new option (text top)
_"Long answer: There is no correct way to center a string. I probably can center them based on individual character's visual center, but they will appear to be on different line. I can also calculate the center based on ascender and descender of the font, which are the highest and lowest point in the font. The pros of this approach is that the whole string will be on the same baseline. However, in your case, this approach will make the text off the center. Therefore, the only way to fix this is to add new options."_
So issue can be closet.
