### ISSUE TITLE
验证码不太友好...能否设置不分大小写

### ISSUE THREAD

**Issue by ZhangLorne** [lemonce/svg-captcha#19]
验证码不太友好...能否设置不分大小写

**Comment by PocketHDJ** [comment]
你说的是验证码的字符串密码吗？你可以把他转成小写的再验证啊

**Comment by lichaozhy** [comment]
你是指验证阶段不区分大小写吗？如果是，恕我直言，对带captcha的请求的验证逻辑是由你来控制的。可以以考虑把验证码的字符串转化为RegExp 编译为 i 模式。使用RegExp的test方法做匹配。

### 抛出验证码的请求

```js
req.session.captchaReg = new RegExp(captcha.text, i);
```

### 检查验证码的中间件

```js
if (!req.session.captchaReg.test(req.query.captcha)) {
  throw '400';
};
```

**Comment by snowdream** [comment]
是否可以设置，展示的验证码图片中，都用大写，或都用小写。
