### ISSUE TITLE
can it be colorfully?

### ISSUE THREAD

**Issue by smancang** [lemonce/svg-captcha#2]
it's good and simple, can it be more optional, such as set text color, the background color and so on.

**Comment by steambap** [comment]
What kind of options would you like ? e.g. {color: true, backgroundColor: true} or you want specify a color like {color: '#fe4336') ?

**Comment by smancang** [comment]
I like the latter.I find a package called svg-captcha-color https://git.coding.net/ncbql/svg-captcha-color.git. It looks like this package and has more options.

**Comment by steambap** [comment]
Thanks for the reference, I'll add the color option.

**Comment by steambap** [comment]
Somehow I cannot push code to github right now. However, I have published a new version to npm which you can try with new options {color: true, background: '#212121'}.

**Comment by steambap** [comment]
Another update. Now you don't have to set color option when background options is set. 

If you still unhappy about some options, feel free to open this again

**Comment by BryanGrezeszak** [comment]
As far as I can tell, it is now always colored, regardless of how you set the `color` option.

**Comment by steambap** [comment]
If you set background option, it will always colored. If you want black and white, do not set background color.

**Comment by BryanGrezeszak** [comment]
Got it, thanks.
