### ISSUE TITLE
use it in mobile

### ISSUE THREAD

**Issue by luohao8023** [lemonce/svg-captcha#21]
**Do you want to request a *feature* or report a *bug*?**

**If this is a feature request, what is motivation for changing the behavior?**

**If it is a bug, which version of svg-captcha are you using?**

**What is the current behavior?**

**What is the expected behavior?**

**Step to reproduce the bug or other relevant information**

**Comment by luohao8023** [comment]
I set the SVG's size to adjust the screen successfully,but the font doesn't.

**Comment by lichaozhy** [comment]
I am very sorry. I had fixed it in v1.3.12. I've been busy designing v3.x to solve the problems thoroughly but more time need. The new release will solve a series of problems and provide more graceful APIs. 

Thanks for your support.
