### ISSUE TITLE
Why size 4 can generate size 4/3/2 captcha ?

### ISSUE THREAD

**Issue by hugojing** [lemonce/svg-captcha#4]
This is my code:

```js
svgCaptcha.randomText({
    size: 4,
    ignoreChars: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
})
```

This code can generate captcha such as 3018, 729, 91.

I think setup that size 4 should generate 3018, 0729, 0091, etc.

What's your think?

Thanks for your works.

svg-captcha is a great npm package.

**Comment by steambap** [comment]
I'm unable to reproduce your problem with the most recent version. Which version are you using?  
  
If you update to the latest version, you can write:
```JavaScript
// instead of writing all the letters, just declare that you want numbers only
svgCaptcha.options.charPreset = '0123456789';
// create captcha
const captcha = svgCaptcha.create();
// assign captcha text to session and send captcha data to client
```
  
That said, I am happy to work this out if you do not want to update the package.

**Comment by steambap** [comment]
I just rechecked your word, are you saying that `svgCaptcha.randomText` methods returns a number like 729 or 91 instead of a string like '0729' or '0091'

**Comment by hugojing** [comment]
Yes.

**Comment by hugojing** [comment]
突然意识到你可能是中国人。。。

啊我的蹩脚的英语。。(*/ω╲*)

**Comment by steambap** [comment]
npm ls svg-captcha  
  
你在你的项目目录下运行这个命令，看看是哪个版本

**Comment by hugojing** [comment]
1.0.7

我升级到最新版试一下。

**Comment by hugojing** [comment]
试了一下，应该旧版和最新版生成的是对的 string， 是我弄错了，抱歉。
