### ISSUE TITLE
关于破解难度

### ISSUE THREAD

**Issue by ugrg** [lemonce/svg-captcha#7]
我看了一下响应的结果，在结果中，我重点关注了Ｃ的表达形式，发现重复的几次调用会出现一段完相同的路径，而这个路径则指表达出Ｃ来了，那么我有理由可以相信，你这里所有的路径并不是实时生成的，或只能按某些特定的规则生成，这会导致结果集是在一个可控范围，应该很容易被暴力搜索出来的．

**Comment by steambap** [comment]
从数学的角度讲，svg只描述了点，所以确实比描述所有像素点的图片更容易暴力破解。

但是话说回来，那个 c 是那条干扰线，所以假设你可以移除干扰线，然后你会怎么暴力破解呢？

**Comment by ugrg** [comment]
你好：
    没想到这么快得到的回复，实在让我感到意外，
    不过，有邮件的话我也可以提供给你一些实例了，这样说的更清楚些，我最近在头痛验证码的事．

    从你们提供的ＤＥＭＯ中，我每次请求获得的结果应该是一个这样一个结果．
    其结果从内容上来说，与文本无异，可以视为文来处理．接下来，我们要做的一件事是，反复调用你的生成验证码接口，通过人工的方式来识别内容，并做好记录．
    在我记录的一组数据当中，可以明显的发现，以下这个path表达出来的是一个小写的c,而在多次反复调用时，这个串会重复出现，这就为我们未来识别出c打下了基础．
<path xmlns="http://www.w3.org/2000/svg" fill="#111" d="M90.36 41.26L87.35 41.10Q84.95 40.99 84.16 40.87Q82.33 40.53 81.15 39.66Q79.85 38.25 79.63 34.90Q79.59 34.40 79.51 33.18Q79.51 32.77 79.43 31.66Q79.40 30.82 79.43 30.10Q79.63 28.16 80.65 27.40Q82.59 26.26 87.43 26.03Q89.45 25.91 90.25 25.91Q91.73 25.91 93.10 26.22Q92.53 27.47 92.00 29.30Q91.50 29.38 91.01 29.34Q90.89 29.30 90.36 29.19L89.41 28.96Q88.34 28.69 87.73 28.73Q83.01 28.81 82.40 31.62Q82.14 32.77 82.21 33.72Q82.37 36.31 83.60 37.39Q84.84 38.48 87.43 38.51Q88.91 38.55 89.64 38.25L90.67 37.75Q91.20 37.52 91.77 37.45Q92.00 39.24 92.38 40.53Q92.15 40.91 90.36 41.26M93.60 44.19Q93.98 44.23 94.81 44.30Q95.46 44.34 95.80 43.77Q94.59 41.67 94.09 39.58Q93.75 39.54 93.29 39.54Q92.87 39.54 92.49 39.73Q92.15 38.48 92.00 37.07Q91.39 36.99 90.17 37.56Q88.95 38.13 88.46 38.13Q88.00 38.17 87.39 38.13Q86.48 38.10 84.50 37.52Q84.16 36.80 84.19 35.66Q84.38 31.43 89.33 30.90Q90.02 30.90 91.39 31.24Q92.76 31.59 93.48 31.55Q93.90 29.30 94.59 27.47Q94.21 27.36 93.83 27.28L93.06 27.21Q93.25 26.71 93.63 25.84Q92.11 25.49 90.55 25.49Q88.15 25.49 83.77 25.88Q81.83 26.03 80.27 27.02Q79.05 27.97 79.05 29.87Q79.05 30.29 79.17 31.51Q79.24 32.54 79.21 33.15Q79.24 35.05 79.97 38.78Q80.35 39.62 80.84 40.11L81.07 40.34L81.11 40.34Q82.14 42.47 86.06 43.08Q89.22 43.58 91.88 43.84Q92.68 43.92 93.60 44.19Z"/>
    应该说，经过不长的时间，我有理由相信，这个验证码的模块中所有的字符对应的口串都会被一一对应上，接下来要做的事就简单多了，做一个数据库，拿到path后，从数据库中进行查询，找到对应的字符．

    关于干扰线，按数据库查找的办法，就是没找到对应的解，则就可以认为这是一条干扰线，不需要关心他．

以下内容是我找出来的小写c在各位上对应的path
c1
<path xmlns="http://www.w3.org/2000/svg" fill="#444" d="M31.16 41.26L28.15 41.10Q25.75 40.99 24.96 40.87Q23.13 40.53 21.95 39.66Q20.65 38.25 20.43 34.90Q20.39 34.40 20.31 33.18Q20.31 32.77 20.23 31.66Q20.20 30.82 20.23 30.10Q20.43 28.16 21.45 27.40Q23.39 26.26 28.23 26.03Q30.25 25.91 31.05 25.91Q32.53 25.91 33.90 26.22Q33.33 27.47 32.80 29.30Q32.30 29.38 31.81 29.34Q31.69 29.30 31.16 29.19L30.21 28.96Q29.14 28.69 28.53 28.73Q23.81 28.81 23.20 31.62Q22.94 32.77 23.01 33.72Q23.17 36.31 24.40 37.39Q25.64 38.48 28.23 38.51Q29.71 38.55 30.44 38.25L31.47 37.75Q32.00 37.52 32.57 37.45Q32.80 39.24 33.18 40.53Q32.95 40.91 31.16 41.26M34.40 44.19Q34.78 44.23 35.61 44.30Q36.26 44.34 36.60 43.77Q35.39 41.67 34.89 39.58Q34.55 39.54 34.09 39.54Q33.67 39.54 33.29 39.73Q32.95 38.48 32.80 37.07Q32.19 36.99 30.97 37.56Q29.75 38.13 29.26 38.13Q28.80 38.17 28.19 38.13Q27.28 38.10 25.30 37.52Q24.96 36.80 24.99 35.66Q25.18 31.43 30.13 30.90Q30.82 30.90 32.19 31.24Q33.56 31.59 34.28 31.55Q34.70 29.30 35.39 27.47Q35.01 27.36 34.63 27.28L33.86 27.21Q34.05 26.71 34.43 25.84Q32.91 25.49 31.35 25.49Q28.95 25.49 24.57 25.88Q22.63 26.03 21.07 27.02Q19.85 27.97 19.85 29.87Q19.85 30.29 19.97 31.51Q20.04 32.54 20.01 33.15Q20.04 35.05 20.77 38.78Q21.15 39.62 21.64 40.11L21.87 40.34L21.91 40.34Q22.94 42.47 26.86 43.08Q30.02 43.58 32.68 43.84Q33.48 43.92 34.40 44.19Z"/>
c2
<path xmlns="http://www.w3.org/2000/svg" fill="#333" d="M60.76 41.26L57.75 41.10Q55.35 40.99 54.56 40.87Q52.73 40.53 51.55 39.66Q50.25 38.25 50.03 34.90Q49.99 34.40 49.91 33.18Q49.91 32.77 49.83 31.66Q49.80 30.82 49.83 30.10Q50.03 28.16 51.05 27.40Q52.99 26.26 57.83 26.03Q59.85 25.91 60.65 25.91Q62.13 25.91 63.50 26.22Q62.93 27.47 62.40 29.30Q61.90 29.38 61.41 29.34Q61.29 29.30 60.76 29.19L59.81 28.96Q58.74 28.69 58.13 28.73Q53.41 28.81 52.80 31.62Q52.54 32.77 52.61 33.72Q52.77 36.31 54.00 37.39Q55.24 38.48 57.83 38.51Q59.31 38.55 60.04 38.25L61.07 37.75Q61.60 37.52 62.17 37.45Q62.40 39.24 62.78 40.53Q62.55 40.91 60.76 41.26M64.00 44.19Q64.38 44.23 65.21 44.30Q65.86 44.34 66.20 43.77Q64.99 41.67 64.49 39.58Q64.15 39.54 63.69 39.54Q63.27 39.54 62.89 39.73Q62.55 38.48 62.40 37.07Q61.79 36.99 60.57 37.56Q59.35 38.13 58.86 38.13Q58.40 38.17 57.79 38.13Q56.88 38.10 54.90 37.52Q54.56 36.80 54.59 35.66Q54.78 31.43 59.73 30.90Q60.42 30.90 61.79 31.24Q63.16 31.59 63.88 31.55Q64.30 29.30 64.99 27.47Q64.61 27.36 64.23 27.28L63.46 27.21Q63.65 26.71 64.03 25.84Q62.51 25.49 60.95 25.49Q58.55 25.49 54.17 25.88Q52.23 26.03 50.67 27.02Q49.45 27.97 49.45 29.87Q49.45 30.29 49.57 31.51Q49.64 32.54 49.61 33.15Q49.64 35.05 50.37 38.78Q50.75 39.62 51.24 40.11L51.47 40.34L51.51 40.34Q52.54 42.47 56.46 43.08Q59.62 43.58 62.28 43.84Q63.08 43.92 64.00 44.19Z"/>
c3
<path xmlns="http://www.w3.org/2000/svg" fill="#222" d="M90.36 41.26L87.35 41.10Q84.95 40.99 84.16 40.87Q82.33 40.53 81.15 39.66Q79.85 38.25 79.63 34.90Q79.59 34.40 79.51 33.18Q79.51 32.77 79.43 31.66Q79.40 30.82 79.43 30.10Q79.63 28.16 80.65 27.40Q82.59 26.26 87.43 26.03Q89.45 25.91 90.25 25.91Q91.73 25.91 93.10 26.22Q92.53 27.47 92.00 29.30Q91.50 29.38 91.01 29.34Q90.89 29.30 90.36 29.19L89.41 28.96Q88.34 28.69 87.73 28.73Q83.01 28.81 82.40 31.62Q82.14 32.77 82.21 33.72Q82.37 36.31 83.60 37.39Q84.84 38.48 87.43 38.51Q88.91 38.55 89.64 38.25L90.67 37.75Q91.20 37.52 91.77 37.45Q92.00 39.24 92.38 40.53Q92.15 40.91 90.36 41.26M93.60 44.19Q93.98 44.23 94.81 44.30Q95.46 44.34 95.80 43.77Q94.59 41.67 94.09 39.58Q93.75 39.54 93.29 39.54Q92.87 39.54 92.49 39.73Q92.15 38.48 92.00 37.07Q91.39 36.99 90.17 37.56Q88.95 38.13 88.46 38.13Q88.00 38.17 87.39 38.13Q86.48 38.10 84.50 37.52Q84.16 36.80 84.19 35.66Q84.38 31.43 89.33 30.90Q90.02 30.90 91.39 31.24Q92.76 31.59 93.48 31.55Q93.90 29.30 94.59 27.47Q94.21 27.36 93.83 27.28L93.06 27.21Q93.25 26.71 93.63 25.84Q92.11 25.49 90.55 25.49Q88.15 25.49 83.77 25.88Q81.83 26.03 80.27 27.02Q79.05 27.97 79.05 29.87Q79.05 30.29 79.17 31.51Q79.24 32.54 79.21 33.15Q79.24 35.05 79.97 38.78Q80.35 39.62 80.84 40.11L81.07 40.34L81.11 40.34Q82.14 42.47 86.06 43.08Q89.22 43.58 91.88 43.84Q92.68 43.92 93.60 44.19Z"/>
c4
<path xmlns="http://www.w3.org/2000/svg" fill="#333" d="M119.96 41.26L116.95 41.10Q114.55 40.99 113.76 40.87Q111.93 40.53 110.75 39.66Q109.45 38.25 109.23 34.90Q109.19 34.40 109.11 33.18Q109.11 32.77 109.03 31.66Q109.00 30.82 109.03 30.10Q109.23 28.16 110.25 27.40Q112.19 26.26 117.03 26.03Q119.05 25.91 119.85 25.91Q121.33 25.91 122.70 26.22Q122.13 27.47 121.60 29.30Q121.10 29.38 120.61 29.34Q120.49 29.30 119.96 29.19L119.01 28.96Q117.94 28.69 117.33 28.73Q112.61 28.81 112.00 31.62Q111.74 32.77 111.81 33.72Q111.97 36.31 113.20 37.39Q114.44 38.48 117.03 38.51Q118.51 38.55 119.24 38.25L120.27 37.75Q120.80 37.52 121.37 37.45Q121.60 39.24 121.98 40.53Q121.75 40.91 119.96 41.26M123.20 44.19Q123.58 44.23 124.41 44.30Q125.06 44.34 125.40 43.77Q124.19 41.67 123.69 39.58Q123.35 39.54 122.89 39.54Q122.47 39.54 122.09 39.73Q121.75 38.48 121.60 37.07Q120.99 36.99 119.77 37.56Q118.55 38.13 118.06 38.13Q117.60 38.17 116.99 38.13Q116.08 38.10 114.10 37.52Q113.76 36.80 113.79 35.66Q113.98 31.43 118.93 30.90Q119.62 30.90 120.99 31.24Q122.36 31.59 123.08 31.55Q123.50 29.30 124.19 27.47Q123.81 27.36 123.43 27.28L122.66 27.21Q122.85 26.71 123.23 25.84Q121.71 25.49 120.15 25.49Q117.75 25.49 113.37 25.88Q111.43 26.03 109.87 27.02Q108.65 27.97 108.65 29.87Q108.65 30.29 108.77 31.51Q108.84 32.54 108.81 33.15Q108.84 35.05 109.57 38.78Q109.95 39.62 110.44 40.11L110.67 40.34L110.71 40.34Q111.74 42.47 115.66 43.08Q118.82 43.58 121.48 43.84Q122.28 43.92 123.20 44.19Z"/>


补充一下可能的解决方案：
    １.经过我的观察，数据中有Ｍ开头的坐标，这是一个标记位，可以在生成path时将所有Ｍ开头的进行拆分，生成很多不同的线，而不是现在每个字符对应一个path,
    ２.对Ｍ中的坐标进行变换，坐标数据偏差一点，对实际的显示效果不会有太大影响．
    ３.想办法加入扭曲，变形，使坐标数据产生较大的差异，这个我没想到有什么办法，不过Ｑ使用的是二次贝叶丝曲线，估计解应该是在这上面．




163.com
 
发件人： Weilin Shi
发送时间： 2017-03-07 21:10
收件人： lemonce/svg-captcha
抄送： ugrg; Author
主题： Re: [lemonce/svg-captcha] 关于破解难度 (#7)
从数学的角度讲，svg只描述了点，所以确实比描述所有像素点的图片更容易暴力破解。
但是话说回来，那个 c 是那条干扰线，所以假设你可以移除干扰线，然后你会怎么暴力破解呢？

**Comment by steambap** [comment]
首先，svg路径生成是引用的opentype.js，我们只是做了些微小的工作，如果对防破解有更高的要求的话，对结果进行replace就行。
```JavaScript
svg.replace(/\d+(\.\d+)?/g, function (match) {
  return parseInt(match, 10) + math.random() * 2 - 1;
});
```

我也很愿意研究矩阵变幻，二次贝叶丝曲线，但是那样不仅需要时间调适，抓bug，而且Node并不擅长计算，会对生成时间有很大影响，我也许会考虑未来增加，但没有任何保证。

**Comment by laola2013** [comment]
想问一下楼主，在您完成svg-captcha后，有自己去验证一下关于svg图形验证码的防破解指数有多高吗

**Comment by ugrg** [comment]
你好:
    不太理解破解指数是个什么概念,但如果现有代码不做变更的话,我可以做到百分之百识别.



163.com
 
发件人： Little Bee
发送时间： 2017-03-28 13:56
收件人： lemonce/svg-captcha
抄送： ugrg; Author
主题： Re: [lemonce/svg-captcha] 关于破解难度 (#7)
想问一下楼主，在您完成svg-captcha后，有自己去验证一下关于svg图形验证码的防破解指数有多高吗

**Comment by steambap** [comment]
非常惭愧，我没有像他那样从数学的角度验证防破解指数。我只能说这个模块完成我们自己网站上的验证码的需求，暂时还没有遇到过验证码被破解的情况。

从另一个角度讲，这个模块的代码是开源的，如果只是照搬我在readme中所写的代码，那肯定会很容易被破解。但只要你稍微对结果做一下修饰，比如我之前写的那个 replace ，就至少不会让别人抓到数字上的规律。

**Comment by laola2013** [comment]
非常感谢您的开源，最近公司项目想要更换验证码，在GitHub上逛了一圈后，觉得您的svg-captcha挺不错的，首先是没什么依赖，其次是非常适用node项目，而且简单易用，我在本地尝试了一下，整体效果都很好，现在只是担心容易被恶意程序破解，我会采用您说的方案，对数字上做些处理的，希望博主日后能完善这方面的问题。

由衷地感谢您对开源社区的贡献。

**Comment by steambap** [comment]
@ugrg  我在最新的版本里面加入对路径的随机化，你看看还有没有办法能识别。

**Comment by steambap** [comment]
@laola2013 感谢您的支持，我会不断改进这个项目的。

**Comment by ganlvtech** [comment]
Have you think about combining path together?
[SVG Optimizer](https://github.com/svg/svgo), an node.js tool, can merge multiple path together. [Online demo](https://jakearchibald.github.io/svgomg/)

It may increase the difficulty. But I don't think It's really difficult enough for a computer to guess the matching number or alphabet.

**Comment by lsycxyj** [comment]
图形验证码的其中一个破解大难点在于字符分割，这项目生成的svg帮破解者都分割好了，用神经网络可以轻易破掉

**Comment by lichaozhy** [comment]
关于对付神经网络，图形验证码还有很多优化空间

* 随机增加碰撞或重叠
* 随机使用更多的字体
* 使用中文或更广泛的字符集合
* 增加验证码长度
* 随机长度验证码
* 栅格化扭曲
* 增加与字体等粗的干扰线连接轮廓
* 增加与字符相连的短干扰线
* 增加用于干扰的字符轮廓（视觉上能够被忽略的）

**以上增强** 对开销无明显增加，都是基于映射和计算的

* svg转其他位图格式

**转换到位图**相关功能的模块在社区是比较成熟的，相比直接生成位图使用复杂的接口，svg标准给我们提供了更多的便利。

实际上关于破解，我认为可以将很多维度加入进来，只要编程接口足够方便，策略整体更换更加动态灵活，对于机器学习来说，还是又很高破解门槛的。

总的来说，svg-captcha暂时的定位是能帮助各位工程界同行满足项目合同需求，提供一些开发便利。

但也十分感谢来自科研工作者的关注，督促我们做的更好。

**Comment by QQ2737499951** [comment]
> 关于对付神经网络，图形验证码还有很多优化空间
> 
> * 随机增加碰撞或重叠
> * 随机使用更多的字体
> * 使用中文或更广泛的字符集合
> * 增加验证码长度
> * 随机长度验证码
> * 栅格化扭曲
> * 增加与字体等粗的干扰线连接轮廓
> * 增加与字符相连的短干扰线
> * 增加用于干扰的字符轮廓（视觉上能够被忽略的）
> 
> **以上增强** 对开销无明显增加，都是基于映射和计算的
> 
> * svg转其他位图格式
> 
> **转换到位图**相关功能的模块在社区是比较成熟的，相比直接生成位图使用复杂的接口，svg标准给我们提供了更多的便利。
> 
> 实际上关于破解，我认为可以将很多维度加入进来，只要编程接口足够方便，策略整体更换更加动态灵活，对于机器学习来说，还是又很高破解门槛的。
> 
> 总的来说，svg-captcha暂时的定位是能帮助各位工程界同行满足项目合同需求，提供一些开发便利。
> 
> 但也十分感谢来自科研工作者的关注，督促我们做的更好。

现在神经网络非常发达。任意验证码都能快速识别破解。做成识别模型，不管怎样变化，人眼都要能识别出来。只要标注出答案，训练就可以了。面对深度学习，目前字符类验证码全线崩溃。这个不是作者能解决的。

不过可以多加一些汉字、字符和大小写混杂的，增加破解的难度。

谢谢作者的无私贡献！
