### ISSUE TITLE
圖片空白寬度可否增加參數設定

### ISSUE THREAD

**Issue by gohiei** [lemonce/svg-captcha#8]
生成的圖片上下會有留白
但在圖片較小的情況(如：w x h = 40 x 18), 
那個空白反而壓縮到了文字可生成的大小 (原本預期佔滿圖片).
是否有考慮新增參數讓使用者自訂呢？

**Comment by steambap** [comment]
确实得增加相应得参数。
由于我自己用的时候都是用的默认的宽高参数，所以没有想到宽高改变会有这种需求。

**Comment by steambap** [comment]
但是在我发布新版本之前，你或许可以考虑先用css来增加一点空白？

**Comment by gohiei** [comment]
目前我是採用 css 裁切掉空白來解決此問題。

**Comment by steambap** [comment]
我发布了 1.3.4 版本，你先试试这个，试着调整一下字体大小参数。

情况就是，图片上下是否有留白是由字体和字体渲染库来决定。参数是ascender和descender，就是字母的基线到所有字母的最高点和最低点的距离。我在调用Opentype.js的时候，计算参数没有设对，导致上下的留白大小不一样。所以你试试新版吧。
